# Update image first: 
# docker compose pull && docker compose -f docker-compose.test.yaml up -d

services:
  bhp:
    container_name: bhp-test
    image: lkeme/bilihelper-personal:test
    stdin_open: true
    tty: true
    restart: on-failure:5
    volumes:
      - ./profile/user:/app/profile/user
    network_mode: bridge
    ports:
      - "50001:50001"
    environment:
      BRANCH: dev
      CAPTCHA: 1
