from activity_index.models.activity_lottery import build_activity_lottery_record
from activity_index.models.charge_lottery import build_charge_lottery_record
from activity_index.models.interactive_lottery import build_interactive_lottery_record
from activity_index.models.reservation_lottery import build_reservation_lottery_record
from activity_index.writers.json_writer import wrap_payload


def test_wrap_payload_uses_shared_envelope():
    payload = wrap_payload([{"title": "demo"}])
    assert payload["code"] == 200
    assert payload["remarks"] == "generated by tools/activity_index"
    assert payload["data"] == [{"title": "demo"}]


def test_activity_lottery_schema_has_required_fields():
    record = build_activity_lottery_record()
    assert sorted(record.keys()) == sorted(
        [
            "title",
            "url",
            "page_id",
            "activity_id",
            "lottery_id",
            "start_time",
            "end_time",
            "source_cv_id",
            "source_url",
            "publish_time",
            "update_time",
        ]
    )


def test_interactive_lottery_schema_has_required_fields():
    record = build_interactive_lottery_record()
    for key in [
        "title",
        "source_cv_id",
        "source_url",
        "publish_time",
        "draw_time",
        "dynamic_id",
        "dynamic_url",
        "reserve_rid",
        "up_mid",
        "requires_follow",
        "requires_repost",
        "requires_comment",
        "prize_summary",
        "update_time",
    ]:
        assert key in record
    assert "status" not in record


def test_reservation_lottery_schema_has_required_fields():
    record = build_reservation_lottery_record()
    for key in [
        "title",
        "source_cv_id",
        "source_url",
        "publish_time",
        "draw_time",
        "up_mid",
        "up_name",
        "sid",
        "name",
        "jump_url",
        "text",
        "requires_follow",
        "requires_reserve",
        "update_time",
    ]:
        assert key in record
    assert "status" not in record


def test_charge_lottery_schema_has_required_fields():
    record = build_charge_lottery_record()
    for key in [
        "title",
        "source_cv_id",
        "source_url",
        "publish_time",
        "draw_time",
        "prize_summary",
        "requires_charge",
        "update_time",
    ]:
        assert key in record
    assert "status" not in record
