<?php declare(strict_types=1);

namespace Bhp\Plugin\ActivityInfoUpdate\Internal;

use Bhp\Api\Api\X\Activity\ApiActivity;
use Bhp\Log\Log;
use Bhp\Request\Request;
use Bhp\Runtime\Runtime;
use Bhp\User\User;
use RuntimeException;

final class ActivityInfoUpdateRunner
{
    /**
     * @return array{path:string,total_urls:int,valid_records:int,skipped_urls:int}
     */
    public function update(?string $filePath = null, ?string $urls = null): array
    {
        $this->assertAuthenticated();
        $resourcePath = $this->resourcePath();
        $existing = $this->loadExistingData($resourcePath);
        $mergedUrls = $this->mergeUrls(
            $this->extractUrlsFromRecords($existing),
            $this->parseUrlsArgument($urls),
            $this->loadUrlsFromFile($filePath)
        );

        if ($mergedUrls === []) {
            throw new RuntimeException('没有可更新的活动链接');
        }

        $records = [];
        $skipped = 0;
        foreach ($mergedUrls as $url) {
            $record = $this->buildRecord($url);
            if ($record === null) {
                $skipped++;
                continue;
            }

            $records[] = $record;
        }

        if ($records === []) {
            throw new RuntimeException('没有可写入的有效活动记录');
        }

        $payload = [
            'code' => 200,
            'remarks' => 'generated by mode:script activity:update-infos',
            'data' => $records,
        ];
        $json = (string)json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
        if ($json === '') {
            throw new RuntimeException('活动索引序列化失败');
        }

        $directory = dirname($resourcePath);
        if (!is_dir($directory)) {
            mkdir($directory, 0777, true);
        }
        file_put_contents($resourcePath, $json . PHP_EOL);

        Log::info("活动索引: 已更新 {$resourcePath}");
        Log::info("活动索引: 总链接 " . count($mergedUrls) . " 条，有效 " . count($records) . " 条，跳过 {$skipped} 条");

        return [
            'path' => $resourcePath,
            'total_urls' => count($mergedUrls),
            'valid_records' => count($records),
            'skipped_urls' => $skipped,
        ];
    }

    protected function assertAuthenticated(): void
    {
        $cookie = Runtime::getInstance()->appContext()->auth('cookie');
        $user = User::parseCookie();
        if ($cookie === '' || $user['csrf'] === '' || $user['uid'] === '') {
            throw new RuntimeException('activity:update-infos 需要当前 profile 已登录');
        }
    }

    protected function resourcePath(): string
    {
        $appRoot = rtrim(str_replace('\\', '/', Runtime::getInstance()->appContext()->appRoot()), '/');

        return $appRoot . '/resources/activity_infos.json';
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    protected function loadExistingData(string $path): array
    {
        if (!is_file($path)) {
            return [];
        }

        $raw = file_get_contents($path);
        if (!is_string($raw) || trim($raw) === '') {
            return [];
        }

        try {
            $decoded = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
        } catch (\Throwable $throwable) {
            throw new RuntimeException("读取 activity_infos.json 失败 {$throwable->getMessage()}");
        }

        $data = $decoded['data'] ?? [];
        if (!is_array($data)) {
            return [];
        }

        return array_values(array_filter($data, static fn (mixed $item): bool => is_array($item)));
    }

    /**
     * @param array<int, array<string, mixed>> $records
     * @return string[]
     */
    protected function extractUrlsFromRecords(array $records): array
    {
        $urls = [];
        foreach ($records as $record) {
            $url = $this->normalizeUrl((string)($record['url'] ?? ''));
            if ($url !== '') {
                $urls[] = $url;
            }
        }

        return $urls;
    }

    /**
     * @return string[]
     */
    protected function parseUrlsArgument(?string $urls): array
    {
        if ($urls === null || trim($urls) === '') {
            return [];
        }

        return $this->normalizeUrlList(preg_split('/[\s,]+/', trim($urls), -1, PREG_SPLIT_NO_EMPTY) ?: []);
    }

    /**
     * @return string[]
     */
    protected function loadUrlsFromFile(?string $path): array
    {
        if ($path === null || trim($path) === '') {
            return [];
        }

        if (!is_file($path) || !is_readable($path)) {
            throw new RuntimeException("链接文件不可读取 {$path}");
        }

        $raw = file_get_contents($path);
        if (!is_string($raw) || trim($raw) === '') {
            return [];
        }

        $urls = [];
        foreach (preg_split('/\R/u', $raw) ?: [] as $line) {
            $line = trim($line);
            if ($line === '' || str_starts_with($line, '#')) {
                continue;
            }

            $urls[] = $line;
        }

        return $this->normalizeUrlList($urls);
    }

    /**
     * @param string[] ...$urlLists
     * @return string[]
     */
    protected function mergeUrls(array ...$urlLists): array
    {
        $merged = [];
        $seen = [];
        foreach ($urlLists as $urlList) {
            foreach ($urlList as $url) {
                if ($url === '' || isset($seen[$url])) {
                    continue;
                }

                $seen[$url] = true;
                $merged[] = $url;
            }
        }

        return $merged;
    }

    /**
     * @param string[] $urls
     * @return string[]
     */
    protected function normalizeUrlList(array $urls): array
    {
        $normalized = [];
        foreach ($urls as $url) {
            $value = $this->normalizeUrl($url);
            if ($value !== '') {
                $normalized[] = $value;
            }
        }

        return $normalized;
    }

    protected function normalizeUrl(string $url): string
    {
        $url = trim($url);
        if ($url === '') {
            return '';
        }

        if (str_starts_with($url, '//')) {
            $url = 'https:' . $url;
        }

        if (!preg_match('~^https?://~i', $url)) {
            return '';
        }

        $parts = parse_url($url);
        if (!is_array($parts)) {
            return '';
        }

        $host = strtolower((string)($parts['host'] ?? ''));
        $path = (string)($parts['path'] ?? '');
        if (!in_array($host, ['www.bilibili.com', 'live.bilibili.com'], true) || !str_contains($path, '/blackboard/era/')) {
            return '';
        }

        return 'https://' . $host . $path;
    }

    /**
     * @return array<string, mixed>|null
     */
    protected function buildRecord(string $url): ?array
    {
        try {
            $html = Request::get('other', $url);
        } catch (\Throwable $throwable) {
            Log::warning("活动索引: 拉取活动页失败 {$url} -> {$throwable->getMessage()}");
            return null;
        }

        $page = (new EraActivityPageParser())->parse($html);
        if ($page === null) {
            Log::warning("活动索引: 活动页解析失败 {$url}");
            return null;
        }

        $lotteryId = trim($page->lotteryId);
        if ($lotteryId === '') {
            Log::warning("活动索引: 活动缺少抽奖ID {$url}");
            return null;
        }

        $response = ApiActivity::myTimes([
            'sid' => $lotteryId,
            'url' => $url,
            'title' => $page->title,
        ]);
        if (($response['code'] ?? -1) !== 0 || !is_array($response['data'] ?? null)) {
            Log::warning("活动索引: 抽奖信息获取失败 {$page->title} {$response['code']} -> {$response['message']}");
            return null;
        }

        $startTime = (int)($response['data']['stime'] ?? 0);
        $endTime = (int)($response['data']['etime'] ?? 0);
        if ($startTime <= 0 || $endTime <= 0) {
            Log::warning("活动索引: 活动时间窗口无效 {$page->title}");
            return null;
        }

        return [
            'title' => trim($page->title),
            'url' => $url,
            'page_id' => trim($page->pageId),
            'activity_id' => trim($page->activityId),
            'lottery_id' => $lotteryId,
            'start_time' => $startTime,
            'end_time' => $endTime,
            'update_time' => date('Y-m-d H:i:s'),
        ];
    }
}
