def wrap_payload(records: list[dict[str, object]]) -> dict[str, object]:
    return {
        "code": 200,
        "remarks": "generated by tools/activity_index",
        "data": records,
    }


def empty_payload() -> dict[str, object]:
    return wrap_payload([])
