<?php declare(strict_types=1);

namespace Bhp\Plugin\Builtin\ActivityInfoUpdate\Internal;

use Bhp\Api\Api\X\Activity\ApiActivity;
use Bhp\Login\AuthFailureClassifier;
use Bhp\Runtime\AppContext;
use RuntimeException;

final class ActivityInfoUpdateRunner
{
    private ?ApiActivity $apiActivity = null;

    /**
     * 初始化 ActivityInfoUpdateRunner
     * @param AppContext $appContext
     */
    public function __construct(
        private readonly AppContext $appContext,
    ) {
    }

    /**
     * @return array{path:string,total_urls:int,valid_records:int,skipped_urls:int}
     */
    public function update(?string $filePath = null, ?string $urls = null): array
    {
        $this->assertAuthenticated();
        $resourcePath = $this->resourcePath();
        $existing = $this->loadExistingData($resourcePath);
        $existingByUrl = $this->indexRecordsByUrl($existing);
        $mergedUrls = $this->mergeUrls(
            $this->extractUrlsFromRecords($existing),
            $this->parseUrlsArgument($urls),
            $this->loadUrlsFromFile($filePath)
        );

        if ($mergedUrls === []) {
            throw new RuntimeException('没有可更新的活动链接');
        }

        $records = [];
        $skipped = 0;
        foreach ($mergedUrls as $url) {
            $record = $this->buildRecord($url);
            if ($record === null) {
                if (isset($existingByUrl[$url])) {
                    $records[] = $existingByUrl[$url];
                }
                $skipped++;
                continue;
            }

            $records[] = $record;
        }

        if ($records === []) {
            throw new RuntimeException('没有可写入的有效活动记录');
        }

        $payload = [
            'code' => 200,
            'remarks' => 'generated by mode:script activity:update-infos',
            'data' => $records,
        ];
        try {
            $json = json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR);
        } catch (\Throwable $throwable) {
            throw new RuntimeException("活动索引序列化失败 {$throwable->getMessage()}", 0, $throwable);
        }

        $directory = dirname($resourcePath);
        if (!is_dir($directory) && !mkdir($directory, 0777, true) && !is_dir($directory)) {
            throw new RuntimeException("活动索引目录创建失败 {$directory}");
        }
        if (file_put_contents($resourcePath, $json . PHP_EOL) === false) {
            throw new RuntimeException("活动索引写入失败 {$resourcePath}");
        }

        $this->appContext->log()->recordInfo("活动索引: 已更新 {$resourcePath}");
        $this->appContext->log()->recordInfo("活动索引: 总链接 " . count($mergedUrls) . " 条，有效 " . count($records) . " 条，跳过 {$skipped} 条");

        return [
            'path' => $resourcePath,
            'total_urls' => count($mergedUrls),
            'valid_records' => count($records),
            'skipped_urls' => $skipped,
        ];
    }

    /**
     * 断言Authenticated
     * @return void
     */
    private function assertAuthenticated(): void
    {
        $cookie = $this->appContext->auth('cookie');
        if ($cookie === '' || $this->appContext->csrf() === '' || $this->appContext->uid() === '') {
            throw new RuntimeException('activity:update-infos 需要当前 profile 已登录');
        }
    }

    /**
     * 处理资源Path
     * @return string
     */
    private function resourcePath(): string
    {
        $appRoot = rtrim(str_replace('\\', '/', $this->appContext->appRoot()), '/');

        return $appRoot . '/resources/plugins/ActivityLottery/catalog.json';
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function loadExistingData(string $path): array
    {
        if (!is_file($path)) {
            return [];
        }

        $raw = file_get_contents($path);
        if (!is_string($raw) || trim($raw) === '') {
            return [];
        }

        try {
            $decoded = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
        } catch (\Throwable $throwable) {
            throw new RuntimeException("读取 ActivityLottery catalog.json 失败 {$throwable->getMessage()}");
        }

        $data = $decoded['data'] ?? [];
        if (!is_array($data)) {
            return [];
        }

        return array_values(array_filter($data, static fn (mixed $item): bool => is_array($item)));
    }

    /**
     * @param array<int, array<string, mixed>> $records
     * @return array<string, array<string, mixed>>
     */
    private function indexRecordsByUrl(array $records): array
    {
        $indexed = [];
        foreach ($records as $record) {
            $url = $this->normalizeUrl((string)($record['url'] ?? ''));
            if ($url === '') {
                continue;
            }

            $indexed[$url] = $record;
        }

        return $indexed;
    }

    /**
     * @param array<int, array<string, mixed>> $records
     * @return string[]
     */
    private function extractUrlsFromRecords(array $records): array
    {
        $urls = [];
        foreach ($records as $record) {
            $url = $this->normalizeUrl((string)($record['url'] ?? ''));
            if ($url !== '') {
                $urls[] = $url;
            }
        }

        return $urls;
    }

    /**
     * @return string[]
     */
    private function parseUrlsArgument(?string $urls): array
    {
        if ($urls === null || trim($urls) === '') {
            return [];
        }

        return $this->normalizeUrlList(preg_split('/[\s,]+/', trim($urls), -1, PREG_SPLIT_NO_EMPTY) ?: []);
    }

    /**
     * @return string[]
     */
    private function loadUrlsFromFile(?string $path): array
    {
        if ($path === null || trim($path) === '') {
            return [];
        }

        if (!is_file($path) || !is_readable($path)) {
            throw new RuntimeException("链接文件不可读取 {$path}");
        }

        $raw = file_get_contents($path);
        if (!is_string($raw) || trim($raw) === '') {
            return [];
        }

        $urls = [];
        foreach (preg_split('/\R/u', $raw) ?: [] as $line) {
            $line = trim($line);
            if ($line === '' || str_starts_with($line, '#')) {
                continue;
            }

            $urls[] = $line;
        }

        return $this->normalizeUrlList($urls);
    }

    /**
     * @param string[] ...$urlLists
     * @return string[]
     */
    private function mergeUrls(array ...$urlLists): array
    {
        $merged = [];
        $seen = [];
        foreach ($urlLists as $urlList) {
            foreach ($urlList as $url) {
                if ($url === '' || isset($seen[$url])) {
                    continue;
                }

                $seen[$url] = true;
                $merged[] = $url;
            }
        }

        return $merged;
    }

    /**
     * @param string[] $urls
     * @return string[]
     */
    private function normalizeUrlList(array $urls): array
    {
        $normalized = [];
        foreach ($urls as $url) {
            $value = $this->normalizeUrl($url);
            if ($value !== '') {
                $normalized[] = $value;
            }
        }

        return $normalized;
    }

    /**
     * 标准化URL
     * @param string $url
     * @return string
     */
    private function normalizeUrl(string $url): string
    {
        $url = trim($url);
        if ($url === '') {
            return '';
        }

        if (str_starts_with($url, '//')) {
            $url = 'https:' . $url;
        }

        if (!preg_match('~^https?://~i', $url)) {
            return '';
        }

        $parts = parse_url($url);
        if (!is_array($parts)) {
            return '';
        }

        $host = strtolower((string)($parts['host'] ?? ''));
        $path = (string)($parts['path'] ?? '');
        if (!in_array($host, ['www.bilibili.com', 'live.bilibili.com'], true) || !str_contains($path, '/blackboard/era/')) {
            return '';
        }

        return 'https://' . $host . $path;
    }

    /**
     * @return array<string, mixed>|null
     */
    private function buildRecord(string $url): ?array
    {
        try {
            $html = $this->appContext->request()->getText('other', $url);
        } catch (\Throwable $throwable) {
            $this->appContext->log()->recordWarning("活动索引: 拉取活动页失败 {$url} -> {$throwable->getMessage()}");
            return null;
        }

        $page = (new EraActivityPageParser())->parse($html);
        if ($page === null) {
            $this->appContext->log()->recordWarning("活动索引: 活动页解析失败 {$url}");
            return null;
        }

        $lotteryId = trim($page->lotteryId);
        if ($lotteryId === '') {
            $this->appContext->log()->recordWarning("活动索引: 活动缺少抽奖ID {$url}");
            return null;
        }

        $response = $this->apiActivity()->myTimes([
            'sid' => $lotteryId,
            'url' => $url,
            'title' => $page->title,
        ]);
        (new AuthFailureClassifier())->assertNotAuthFailure($response, "活动索引: 获取{$page->title}抽奖信息时账号未登录");
        if (($response['code'] ?? -1) !== 0 || !is_array($response['data'] ?? null)) {
            $code = $response['code'] ?? 'unknown';
            $message = is_string($response['message'] ?? null) ? $response['message'] : 'unknown';
            $this->appContext->log()->recordWarning("活动索引: 抽奖信息获取失败 {$page->title} {$code} -> {$message}");
            return null;
        }

        $startTime = (int)($response['data']['stime'] ?? 0);
        $endTime = (int)($response['data']['etime'] ?? 0);
        if ($startTime <= 0 || $endTime <= 0) {
            $this->appContext->log()->recordWarning("活动索引: 活动时间窗口无效 {$page->title}");
            return null;
        }

        return [
            'title' => trim($page->title),
            'url' => $url,
            'page_id' => trim($page->pageId),
            'activity_id' => trim($page->activityId),
            'lottery_id' => $lotteryId,
            'start_time' => $startTime,
            'end_time' => $endTime,
            'update_time' => date('Y-m-d H:i:s'),
        ];
    }

    /**
     * 处理APIActivity
     * @return ApiActivity
     */
    private function apiActivity(): ApiActivity
    {
        return $this->apiActivity ??= new ApiActivity($this->appContext->request());
    }
}
