def build_empty_payloads() -> dict[str, dict[str, object]]:
    names = [
        "activity_lottery_infos.json",
        "interactive_lottery_infos.json",
        "reservation_lottery_infos.json",
        "charge_lottery_infos.json",
    ]

    return {
        name: {
            "code": 200,
            "remarks": "generated by tools/activity_index",
            "data": [],
        }
        for name in names
    }
